plugins:
  opencollective_enabled:
    default: true
    client: true
  opencollective_collective_name:
    default: ''
    client: true
  opencollective_access_token:
    default: ''
    client: false
